---
title: "Metaprogramming"
author: "GW Dean"
date: "`r Sys.Date()`"
output: github_document
---
# Notes on Metaprogramming in RStudio
This document is written as a personal project to gain an understanding of Metaprogramming working within the RStudio IDE.

THIS IS A WORK IN PROGRESS. VERY ROUGH.

## Big Picture
library(rlang)
library(lobstr)

### Code is data
expr(mean(x, na.rm = TRUE))

expr(10 + 100 * 1000)

- Captured code is called an *expression*.

capture_it <- function(x) {
  expr(x)
}
capture_it(a + b + c)

capture_it <- function(x) {
  enexpr(x)
}
capture_it(a + b + c)

f <- expr(f(x = 1, y = 2))

f$z <- 3
f

f[[2]] <- NULL
f

### Code is a tree
lobstr::ast(f(a, "b"))

lobstr::ast(f1(f2(a, b), f3(1, f4(2))))

lobstr::ast(1 + 2 * 3)

### Code can generate code
Two main tools can be used to create new trees:
- call2()
- unquoting

call2("f", 1, 2, 3)

call2("+", 1, call2("*", 2, 3))

xx <- expr(x + x)
yy <- expr(y + y)

expr(!!xx / !!yy)

cv <- function(var) {
  var <- enexpr(var)
  expr(sd(!!var) / mean(!!var))
}

cv(x)

cv(x + y)

cv(`)`)

### Evaluation runs code
eval(expr(x + y), env(x = 1, y = 10))

eval(expr(x + y), env(x = 2, y = 100))

x <- 10
y <- 100
eval(expr(x + y))

A major advantage of evaluating code manually is that you can tweak the environment. 

Two main reasons to tweak the environment:
- Temporarily override functions to implement a *domain specific language*.
- Add a *data mask* so you can refer to variables in a data frame as if they are variables in an environment.

### Customising evaluation with functions
"Big Idea" -> binding names to functions allows you to override the behaviour of existing functions.

string_math <- function(x) {
  e <- env(
    caller_env(),
    `+` = function(x, y) paste0(x, y),
    `*` = function(x, y) strrep(x, y)
  )
  eval(enexpr(x), e)
}

name <- "Jim"
string_math("Yo " + name)

string_math(("x" * 2 + "-y") * 3)

*dplyr* takes this idea to an extreme.

library(dplyr)
library(RSQLite)

con <- DBI::dbConnect(RSQLite::SQLite(), filename = ":memory:")

mtcars_db <- copy_to(con, mtcars)

mtcars_db %>%
  filter(cyl > 2) %>%
  select(mpg:hp) %>%
  head(10) %>%
  show_query()

DBI::dbDisconnect(con)

### Customising evaluation with data
df <- data.frame(x = 1:5, y = sample(5))
eval_tidy(expr(x + y), df)

with2 <- function(df, expr) {
  eval_tidy(enexpr(expr), df)
}

with2(df, x + y)

### Quosures
with2 <- function(df, expr) {
  a <- 1000
  eval_tidy(enexpr(expr), df)
}

df <- data.frame(x = 1:3)
a <- 10
with2(df, x + a)

with2 <- function(df, expr) {
  a <- 1000
  eval_tidy(enquo(expr), df)
}

with2(df, x + a)

## Expressions
y <- x * 10

z <- rlang::expr(y <- x * 10)
z

x <- 4
eval(z)
y

### Abstract Syntax Trees
Expressions are also called *abstract syntax trees* because the structure of code is hierarchical and be naturally represented as a tree. 

lobstr::ast(f(x, "y", 1))

lobstr::ast(f(g(1, 2), h(3, 4, i())))

Abstract Syntax Trees only capture structural details of the code, not whitespace or comments:

ast(
  f(x, y) # important!
)

Below is an exception when the whitespace affects the AST.

lobstr::ast(y <- x)

lobstr::ast(y < -x)

These two lines of code are equivalent:

y <- x * 10

`<-`(y, '*'(x, 10))

lobstr::ast(y <- x * 10)

lobstr::ast(`<-`(y, '*'(x, 10)))


